name: JUnitInDocker CI Pipeline

#  - name: "Debug"
#    uses: lhotari/action-upterm@v1

on:
  release:
    types: ["published"]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      # Prepare the environment
      - name: "Clone Code"
        uses: actions/checkout@v2
      - name: "Setup JDK 8"
        uses: actions/setup-java@v1
        with:
          java-version: 8

      # Validate and build binary
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew build

      # Save gradle version
      - name: Fetch project version
        run: |
          version=$(./gradlew -q version)
          echo "Project version is '$version'"
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/libs/JUnitDocker-${{ env.VERSION }}.jar
